<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'titolo' => 'Colosseo',
                'descrizione' => 'Anfiteatro Flavio, simbolo di Roma antica.',
                'indirizzo' => 'Piazza del Colosseo, 1, 00184 Roma RM',
                'latitude' => 41.890214,
                'longitude' => 12.492231,
                'stato' => 'attivo',
                'orari_apertura' => '09:00 - 19:00',
                'prezzo_biglietto' => '€16 - €22',
                'sito_web' => 'https://parcocolosseo.it',
                'telefono' => '+39 0639967700',
                'note_visitatori' => 'Biglietto valido 24 ore per Colosseo, Foro Romano e Palatino.',
            ],
            [
                'titolo' => 'Torre di Pisa',
                'descrizione' => 'Campanile pendente del Duomo di Pisa.',
                'indirizzo' => 'Piazza del Duomo, 56126 Pisa PI',
                'latitude' => 43.722952,
                'longitude' => 10.396597,
                'stato' => 'attivo',
                'orari_apertura' => '09:00 - 18:00',
                'prezzo_biglietto' => '€20 - €27',
                'sito_web' => 'https://www.opapisa.it',
                'telefono' => '+39 050835011',
                'note_visitatori' => 'Accesso alla torre a turni; scale ripide.',
            ],
            [
                'titolo' => 'Duomo di Milano',
                'descrizione' => 'Cattedrale gotica nel cuore di Milano.',
                'indirizzo' => 'Piazza del Duomo, 20122 Milano MI',
                'latitude' => 45.464211,
                'longitude' => 9.191383,
                'stato' => 'attivo',
                'orari_apertura' => '08:00 - 19:00',
                'prezzo_biglietto' => '€7 - €16',
                'sito_web' => 'https://www.duomomilano.it',
                'telefono' => '+39 0272023375',
                'note_visitatori' => 'Abbigliamento consono richiesto.',
            ],
            [
                'titolo' => 'Ponte di Rialto',
                'descrizione' => 'Storico ponte sul Canal Grande a Venezia.',
                'indirizzo' => 'Sestiere San Polo, 30125 Venezia VE',
                'latitude' => 45.437190,
                'longitude' => 12.335188,
                'stato' => 'attivo',
                'orari_apertura' => 'Sempre accessibile',
                'prezzo_biglietto' => 'Gratis',
                'sito_web' => 'https://www.veneziaunica.it',
                'telefono' => null,
                'note_visitatori' => 'Molto affollato nelle ore centrali.',
            ],
            [
                'titolo' => 'Palazzo Pitti',
                'descrizione' => 'Storica residenza dei Medici a Firenze.',
                'indirizzo' => 'Piazza de Pitti, 1, 50125 Firenze FI',
                'latitude' => 43.765407,
                'longitude' => 11.250059,
                'stato' => 'attivo',
                'orari_apertura' => '08:15 - 18:30',
                'prezzo_biglietto' => '€10 - €16',
                'sito_web' => 'https://www.uffizi.it/palazzo-pitti',
                'telefono' => '+39 055294883',
                'note_visitatori' => 'Comprende Galleria Palatina e Giardino di Boboli.',
            ],
            [
                'titolo' => 'Castel del Monte',
                'descrizione' => 'Castello ottagonale di Federico II in Puglia.',
                'indirizzo' => 'Strada Statale 170, 76123 Andria BT',
                'latitude' => 41.084026,
                'longitude' => 16.270933,
                'stato' => 'attivo',
                'orari_apertura' => '09:00 - 19:00',
                'prezzo_biglietto' => '€7 - €10',
                'sito_web' => 'https://musei.puglia.beniculturali.it',
                'telefono' => '+39 0883569696',
                'note_visitatori' => 'Patrimonio UNESCO.',
            ],
            [
                'titolo' => 'Arena di Verona',
                'descrizione' => 'Anfiteatro romano celebre per l’opera.',
                'indirizzo' => 'Piazza Bra, 1, 37121 Verona VR',
                'latitude' => 45.438611,
                'longitude' => 10.994167,
                'stato' => 'attivo',
                'orari_apertura' => '09:00 - 19:00',
                'prezzo_biglietto' => '€10 - €15',
                'sito_web' => 'https://www.arena.it',
                'telefono' => '+39 0458005151',
                'note_visitatori' => 'Eventi serali durante la stagione.',
            ],
            [
                'titolo' => 'Reggia di Caserta',
                'descrizione' => 'Sontuosa residenza reale borbonica.',
                'indirizzo' => 'Viale Douhet, 2/a, 81100 Caserta CE',
                'latitude' => 41.074640,
                'longitude' => 14.327990,
                'stato' => 'attivo',
                'orari_apertura' => '08:30 - 19:30',
                'prezzo_biglietto' => '€10 - €14',
                'sito_web' => 'https://reggiadicaserta.cultura.gov.it',
                'telefono' => '+39 0823272323',
                'note_visitatori' => 'Parco immenso, prevedere tempo per la visita.',
            ],
            [
                'titolo' => 'Pompei',
                'descrizione' => 'Scavi archeologici dell’antica città romana.',
                'indirizzo' => 'Via Villa dei Misteri, 2, 80045 Pompei NA',
                'latitude' => 40.748440,
                'longitude' => 14.487140,
                'stato' => 'attivo',
                'orari_apertura' => '09:00 - 19:00',
                'prezzo_biglietto' => '€16',
                'sito_web' => 'https://www.pompeiisites.org',
                'telefono' => '+39 0818575111',
                'note_visitatori' => 'Si consiglia cappello e acqua in estate.',
            ],
            [
                'titolo' => 'Valle dei Templi',
                'descrizione' => 'Parco archeologico in Sicilia.',
                'indirizzo' => 'Via Panoramica dei Templi, 92100 Agrigento AG',
                'latitude' => 37.290000,
                'longitude' => 13.585833,
                'stato' => 'attivo',
                'orari_apertura' => '08:30 - 19:00',
                'prezzo_biglietto' => '€12',
                'sito_web' => 'https://www.parcovalledeitempli.it',
                'telefono' => '+39 0922621828',
                'note_visitatori' => 'Tramonto spettacolare.',
            ],
            [
                'titolo' => 'Musei Vaticani',
                'descrizione' => 'Complesso museale con la Cappella Sistina.',
                'indirizzo' => 'Viale Vaticano, 00165 Roma RM',
                'latitude' => 41.906487,
                'longitude' => 12.453601,
                'stato' => 'attivo',
                'orari_apertura' => '09:00 - 18:00',
                'prezzo_biglietto' => '€17',
                'sito_web' => 'https://www.museivaticani.va',
                'telefono' => '+39 0669884667',
                'note_visitatori' => 'Prenotazione consigliata.',
            ],
            [
                'titolo' => 'Cinque Terre',
                'descrizione' => 'Cinque borghi sulla riviera ligure.',
                'indirizzo' => '19018 Vernazza SP',
                'latitude' => 44.135000,
                'longitude' => 9.683000,
                'stato' => 'attivo',
                'orari_apertura' => 'Sempre accessibile',
                'prezzo_biglietto' => 'Gratis (parco a pagamento per alcuni servizi)',
                'sito_web' => 'https://www.parconazionale5terre.it',
                'telefono' => null,
                'note_visitatori' => 'Sentieri con vista mare.',
            ],
            [
                'titolo' => 'Matera Sassi',
                'descrizione' => 'Antichi rioni di case scavate nella roccia.',
                'indirizzo' => '75100 Matera MT',
                'latitude' => 40.667000,
                'longitude' => 16.604000,
                'stato' => 'attivo',
                'orari_apertura' => 'Sempre accessibile',
                'prezzo_biglietto' => 'Gratis (musei a pagamento)',
                'sito_web' => 'https://www.comune.matera.it',
                'telefono' => null,
                'note_visitatori' => 'Scarpe comode consigliate.',
            ],
            [
                'titolo' => 'Reggia di Venaria',
                'descrizione' => 'Splendida residenza sabauda vicino Torino.',
                'indirizzo' => 'Piazza della Repubblica, 4, 10078 Venaria Reale TO',
                'latitude' => 45.135278,
                'longitude' => 7.626667,
                'stato' => 'attivo',
                'orari_apertura' => '09:00 - 17:00',
                'prezzo_biglietto' => '€12 - €20',
                'sito_web' => 'https://lavenaria.it',
                'telefono' => '+39 0114992333',
                'note_visitatori' => 'Giardini e mostre temporanee.',
            ],
            [
                'titolo' => 'Trulli di Alberobello',
                'descrizione' => 'Caratteristiche abitazioni in pietra.',
                'indirizzo' => '70011 Alberobello BA',
                'latitude' => 40.783333,
                'longitude' => 17.233333,
                'stato' => 'attivo',
                'orari_apertura' => 'Sempre accessibile',
                'prezzo_biglietto' => 'Gratis',
                'sito_web' => 'https://www.comune.alberobello.ba.it',
                'telefono' => null,
                'note_visitatori' => 'Area molto turistica.',
            ],
            [
                'titolo' => 'Teatro Massimo',
                'descrizione' => 'Grande teatro dell’opera di Palermo.',
                'indirizzo' => 'Piazza Verdi, 90138 Palermo PA',
                'latitude' => 38.121389,
                'longitude' => 13.356389,
                'stato' => 'attivo',
                'orari_apertura' => '09:30 - 18:00',
                'prezzo_biglietto' => '€10',
                'sito_web' => 'https://www.teatromassimo.it',
                'telefono' => '+39 0916053521',
                'note_visitatori' => 'Visite guidate disponibili.',
            ],
            [
                'titolo' => 'Basilica di San Marco',
                'descrizione' => 'Iconica basilica di Venezia in Piazza San Marco.',
                'indirizzo' => 'Piazza San Marco, 328, 30124 Venezia VE',
                'latitude' => 45.434336,
                'longitude' => 12.339793,
                'stato' => 'attivo',
                'orari_apertura' => '09:30 - 17:00',
                'prezzo_biglietto' => '€3 - €5',
                'sito_web' => 'https://www.basilicasanmarco.it',
                'telefono' => '+39 0412708311',
                'note_visitatori' => 'Code frequenti, prenotazione consigliata.',
            ],
            [
                'titolo' => 'Duomo di Firenze',
                'descrizione' => 'Cattedrale di Santa Maria del Fiore con cupola del Brunelleschi.',
                'indirizzo' => 'Piazza del Duomo, 50122 Firenze FI',
                'latitude' => 43.773144,
                'longitude' => 11.255559,
                'stato' => 'attivo',
                'orari_apertura' => '10:15 - 16:45',
                'prezzo_biglietto' => '€15 - €30',
                'sito_web' => 'https://duomo.firenze.it',
                'telefono' => '+39 0552302885',
                'note_visitatori' => 'Accesso alla cupola a turni.',
            ],
            [
                'titolo' => 'Mole Antonelliana',
                'descrizione' => 'Simbolo di Torino, ospita il Museo del Cinema.',
                'indirizzo' => 'Via Montebello, 20, 10124 Torino TO',
                'latitude' => 45.069722,
                'longitude' => 7.693056,
                'stato' => 'attivo',
                'orari_apertura' => '10:00 - 18:00',
                'prezzo_biglietto' => '€12',
                'sito_web' => 'https://www.museocinema.it',
                'telefono' => '+39 0118138564',
                'note_visitatori' => 'Ascensore panoramico.',
            ],
            [
                'titolo' => 'Galleria degli Uffizi',
                'descrizione' => 'Uno dei più importanti musei del mondo.',
                'indirizzo' => 'Piazzale degli Uffizi, 6, 50122 Firenze FI',
                'latitude' => 43.768700,
                'longitude' => 11.255000,
                'stato' => 'attivo',
                'orari_apertura' => '08:15 - 18:50',
                'prezzo_biglietto' => '€12 - €25',
                'sito_web' => 'https://www.uffizi.it',
                'telefono' => '+39 055294883',
                'note_visitatori' => 'Museo molto affollato.',
            ],
            [
                'titolo' => 'San Siro Stadio',
                'descrizione' => 'Stadio Giuseppe Meazza a Milano.',
                'indirizzo' => 'Piazzale Angelo Moratti, 20151 Milano MI',
                'latitude' => 45.478111,
                'longitude' => 9.124000,
                'stato' => 'disattivo',
                'orari_apertura' => 'Variabile per eventi',
                'prezzo_biglietto' => 'Variabile',
                'sito_web' => 'https://www.sansirostadium.com',
                'telefono' => '+39 0248781',
                'note_visitatori' => 'Controllare calendario eventi.',
            ],
            [
                'titolo' => 'Etna Vulcano',
                'descrizione' => 'Vulcano attivo in Sicilia.',
                'indirizzo' => '95019 Zafferana Etnea CT',
                'latitude' => 37.748611,
                'longitude' => 14.999444,
                'stato' => 'in_allarme',
                'orari_apertura' => 'Accesso regolamentato',
                'prezzo_biglietto' => '—',
                'sito_web' => 'https://www.parks.it/parco.etna',
                'telefono' => null,
                'note_visitatori' => 'Seguire le indicazioni della protezione civile.',
            ],
        ];

        // Ensure we have at least 20 by duplicating with minor variations if needed
        while (count($data) < 20) {
            $data[] = [
                'titolo' => 'Monumento '.(count($data) + 1),
                'descrizione' => 'Luogo di interesse turistico.',
                'indirizzo' => 'Indirizzo '.(count($data) + 1).', Italia',
                'latitude' => 42.5 + (mt_rand(-1000, 1000) / 1000),
                'longitude' => 12.5 + (mt_rand(-1000, 1000) / 1000),
                'stato' => ['attivo', 'disattivo', 'in_allarme'][array_rand(['attivo', 'disattivo', 'in_allarme'])],
                'orari_apertura' => '09:00 - 18:00',
                'prezzo_biglietto' => '€10',
                'sito_web' => null,
                'telefono' => null,
                'note_visitatori' => null,
            ];
        }

        Location::query()->upsert($data, ['titolo']);
    }
}
